### ISSUE TITLE
Estilo

### ISSUE THREAD

**Issue by javalfsot** [javalfsot/javalfsot-trabajo01grupotd2024#1]
Buenas, 

he subido los tres ficheros necesarios.

Para el .Rmd y .R, hay que seguir metiendo los problemas que faltan. Creo que sería bastante positivo para la imagen del repositorio y del trabajo que mantengamos un mismo estilo para las cuatro partes. Por supuesto, no tiene que ser la primera que se haya subido, si a alguien se le da bien, que maquete mejor el .Rmd o la estructura del .R pero que lo haga con todos los problemas, no sólo con el suyo.

Gracias.

**Comment by paulagalindo03** [comment]
Acabo de añadir mis enunciados en el archivo enunciados.Rmd. También he cambiado un poco el estilo de los títulos y he añadido algunos saltos de línea para que se vea más claro el conjunto.
