### ISSUE TITLE
Función solución 

### ISSUE THREAD

**Issue by javalfsot** [javalfsot/javalfsot-trabajo01grupotd2024#2]
Para el primer problema, el de la tabla, hay que resolverla mediante varios métodos y en dos criterios distintos. Para agilizar y automatizar ese proceso, he creado una función que podéis utilizar si queréis, que da la salida directamente y explica método, criterio y alternativa óptima. Podéis usarlo en vuestro trabajo individual sin problema si os viene bien. La encontraréis en el fichero .R y también en mi repositorio individual.

Hay un fallo y es que si la solución consta de tres alternativas óptimas, pondría lo siguiente:

... las soluciones son 1 y 2 y 3 .

Debería de existir una coma (,) antes de todas las opciones que no sean la primera y la última.

Si a alguien le apetece arreglarlo, que suba un issue, por favor.

Gracias.

**Comment by frangala3** [comment]
He creado una nueva rama en el repositorio en el que he modificado la función resolucion para intentar solventar el problema.
No he tenido la oportunidad de probar si es correcta la modificación, por lo que os dejo que lo probéis y lo arregléis o digáis si es correcto, cerrando el issue.

**Comment by frangala3** [comment]
He arreglado la función solucion que creé en la rama ya que daba error de sintaxis en cuanto a paréntesis y llaves. La he probado y funciona, por lo que cerraré la rama y modificaré la función solucion en la rama principal.

**Comment by javalfsot** [comment]
Genial, acabo de revisarla y creo que ha quedado perfecta. Gracias
