### ISSUE TITLE
Coherencia tablas en resolucion

### ISSUE THREAD

**Issue by frangala3** [javalfsot/javalfsot-trabajo01grupotd2024#3]
En el fichero resolucion he observado una inchoerencia en cuanto al nombre de las tablas: para el problema 1 tenemos tabla_1, para el problema 2 tenemos tabla_3, para el problema 5 tenemos tabla_2,...
Propongo hacer coincidir el número de la tabla con el del problema, es decir, que el problema 5 tenga tabla_5, el problema 2 tenga tabla_2,...

**Comment by javalfsot** [comment]
Perfecto, ¿tú te encargas de cambiarlo cuando estén todos? No me importa hacerlo 👍

**Comment by paulagalindo03** [comment]
Aprovechando que he añadido la resolución de los problemas 3 y 5, he cambiado los nombres de las tablas para que tenga coherencia. Ahora la "tabla_1" es la correspondiente al ejercicio 1, la "tabla_2" es la correspondiente al ejercicio 2 y así con todas las demás.
