### ISSUE TITLE
Problema 4

### ISSUE THREAD

**Issue by frangala3** [javalfsot/javalfsot-trabajo01grupotd2024#5]
El problema 4 no cumple con los requisitos del trabajo, ya que es una situación real que se resuelve solo de forma favorable.
Como buscamos una tabla a la que haya que hacer todos los criterios con casos favorable y desfavorable, una solución podría ser poner la misma tabla cambiando el enunciado.

**Comment by angelfc23** [comment]
Ya he actualizado el problema, utilizando solo la tabla y quitando el contexto que tenía el enunciado
