### ISSUE TITLE
Problemas Tabla de Decisión 

### ISSUE THREAD

**Issue by angelfc23** [javalfsot/javalfsot-trabajo01grupotd2024#6]
Para que estuviera más completo el trabajo podríamos explicar en una línea de comentario la solución de cada problema, aunque te la de al ejecutarla, para que fuese más práctico visualmente

**Comment by paulagalindo03** [comment]
Me parece buena idea, acabo de comentar las soluciones correspondientes al problema 3

**Comment by frangala3** [comment]
Comentadas las soluciones del problema 2.

**Comment by javalfsot** [comment]
Yo creo que es mejor no comentar la solución, ya que dejas de manera fija una solución que puede cambiar si cambia la tabla 👍

**Comment by frangala3** [comment]
He borrado todos los comentarios que había en el fichero resolucion ya que hemos decidido que mejor borrarlos. Cierro el issue.
