### ISSUE TITLE
Criterio de Wald

### ISSUE THREAD

**Issue by frangala3** [javalfsot/javalfsot-trabajo01grupotd2024#7]
En el primer tipo de problemas (tabla dada y hacer todos los criterios uno a uno) no hemos hecho ninguno el criterio de Wald por olvido. Lo voy a poner para mi problema y dejo que los demás lo añadáis a los vuestros.

**Comment by javalfsot** [comment]
okey, los he añadido para  los problemas 1, 3 y 4
